# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Izpk1FVtv70qgBU_Cgvy1DS-yCaEq43b
"""

import pandas as pd
import numpy as np

data = pd.read_csv('best.csv')

"""data=pd.DataFrame(data)"""

data.columns

data.head()
data.drop_duplicates()



r=data['User Rating']
v=data['Reviews']
c=data['User Rating'].mean()
m=data['Reviews'].quantile(0.7)

data['weighted_rating']=((r*v)+(c*m))/(v+m)

data['weighted_rating']

data.head()

data.sort_values('weighted_rating',ascending=False)

import seaborn as s
import matplotlib.pyplot as plt

plt.bar(x=data['Name'].head(10),height=data['weighted_rating'].head(10))
plt.xticks(rotation=90)
plt.show()



